#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static void CollectScripts(const fs::path& dir, const std::string& includePrefix,
    std::vector<std::string>& outIncludes,
    std::vector<std::string>& outRegisters,
    const std::string& regFunc) {
    for (auto& entry : fs::directory_iterator(dir)) {
        if (entry.is_directory()) {
            CollectScripts(entry.path(), includePrefix + "/" + entry.path().filename().string(),
                outIncludes, outRegisters, regFunc);
            continue;
        }

        if (entry.path().extension() == ".h") {
            std::string name = entry.path().stem().string();
            std::string includePath = includePrefix + "/" + entry.path().filename().string();

            outIncludes.push_back("#include <" + includePath + ">");
            outRegisters.push_back("    registry." + regFunc + "(\"" + name + "\", []() { return std::make_unique<" + name + ">(); });");
        }
    }
}

static std::string NormalizePath(std::string path) {
    if (!path.empty() && path.front() == '"' && path.back() == '"')
        path = path.substr(1, path.size() - 2);

    for (auto& c : path)
        if (c == '\\') c = '/';

    if (!path.empty() && (path.back() == '/' || path.back() == '\\'))
        path.pop_back();

    return path;
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "Usage: ScriptRegistryGenerator <RootDir> <OutputDir>\n";
        return 1;
    }

    std::string rootStr = NormalizePath(argv[1]);
    std::string outStr = NormalizePath(argv[2]);

    fs::path rootDir = rootStr;
    fs::path outputDir = outStr;

    fs::path enemyDir = rootDir / "include" / "DelusiveScripts" / "EnemyLogic";
    fs::path uiDir = rootDir / "include" / "DelusiveScripts" / "UI";
    fs::path outputFile = outputDir / "AutoGeneratedScripts.cpp";

    std::vector<std::string> includes;
    std::vector<std::string> behaviourRegs;
    std::vector<std::string> uiRegs;

    if (fs::exists(enemyDir)) CollectScripts(enemyDir, "DelusiveScripts/EnemyLogic", includes, behaviourRegs, "RegisterBehaviour");
    if (fs::exists(uiDir)) CollectScripts(uiDir, "DelusiveScripts/UI", includes, uiRegs, "RegisterUIScript");

    std::ofstream out(outputFile);
    if (!out.is_open()) {
        std::cerr << "Failed to open output file: " << outputFile << "\n";
        std::cerr << "Root dir: " << rootDir << std::endl;
        std::cerr << "Passed in value: " << argv[1] << std::endl;
        std::cerr << "Passed in value: " << argv[2] << std::endl;
        return 1;
    }

    out << "// AutoGeneratedScripts.cpp (Generated by ScriptRegistryGenerator)\n";
    out << "#include <DelusiveExternal/ScriptRegistry.h>\n";
    for (auto& inc : includes) out << inc << "\n";

    out << "\nextern \"C\" __declspec(dllexport)\n";
    out << "void InitializeScripts(ScriptRegistry& registry) {\n";
    for (auto& reg : behaviourRegs) out << reg << "\n";
    for (auto& reg : uiRegs) out << reg << "\n";
    out << "}\n\n";

    out << "extern \"C\" __declspec(dllexport)\n";
    out << "void UpdateScripts(float deltaTime) {}\n\n";
    out << "extern \"C\" __declspec(dllexport)\n";
    out << "void ShutdownScripts() {}\n";

    std::cout << "Generated: " << outputFile << "\n";
    return 0;
}