// ScriptRegistry.cpp
#include <Delusive/Scripting/ScriptRegistry.h>
#include <Delusive/Scripting/UIScript.h>
#include <iostream>
#include <filesystem>

void InitializeScripts(ScriptRegistry& registry);
//typedef void (*InitializeScriptsFn)(ScriptRegistry&);
//typedef void (*ShutdownScriptsFn)();

void ScriptRegistry::Init() {
    InitializeScripts(*this);

    if (loggingEnabled) {
        std::cout << "[ScriptRegistry] Registered "
            << enemyLogicFactories.size()
            << " enemy scripts and "
            << uiFactories.size()
            << " UI scripts.\n";
    }
}

std::unique_ptr<BehaviourScript> ScriptRegistry::CreateEnemyLogic(const std::string& name) const {
    auto it = enemyLogicFactories.find(name);
    if (it == enemyLogicFactories.end()) {
        if (loggingEnabled) {
            std::cout << "[ScriptRegistry] ERROR: EnemyLogic script '"
                << name
                << "' not found! (Did the generator include it?)\n";
        }
        return nullptr;
    }

    if (loggingEnabled) {
        std::cout << "[ScriptRegistry] Creating EnemyLogic: " << name << "\n";
    }

    return it->second();
}

std::unique_ptr<UIScript> ScriptRegistry::CreateUIScript(const std::string& name) const {
    auto it = uiFactories.find(name);
    if (it == uiFactories.end()) {
        if (loggingEnabled) {
            std::cout << "[ScriptRegistry] ERROR: UIScript '"
                << name
                << "' not found! (Check AutoGeneratedScripts.cpp)\n";
        }
        return nullptr;
    }

    if (loggingEnabled) {
        std::cout << "[ScriptRegistry] Creating UIScript: " << name << "\n";
    }

    return it->second();
}