#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

// Helper function to collect class names from filenames
static std::vector<std::string> CollectScripts(const std::string& directory) {
    std::vector<std::string> result;
    if (!fs::exists(directory)) return result;

    for (const auto& entry : fs::directory_iterator(directory)) {
        if (entry.is_regular_file()) {
            std::string name = entry.path().stem().string(); // “MyZombieScript.h” -> “MyZombieScript”
            result.push_back(name);
        }
    }
    return result;
}

int main(int argc, char** argv)
{
    if (argc < 4) {
        std::cerr << "Usage: ScriptAutoGen <EnemyLogicDir> <UIDir> <OutputFile>\n";
        return 1;
    }

    const std::string enemyDir = argv[1];
    const std::string uiDir = argv[2];
    const std::string output = argv[3];

    auto enemyScripts = CollectScripts(enemyDir);
    auto uiScripts = CollectScripts(uiDir);

    std::ofstream out(output);
    if (!out.is_open()) {
        std::cerr << "Failed to write to " << output << "\n";
        return 1;
    }

    // Begin output file
    out << "// Auto-generated by ScriptAutoGen — DO NOT EDIT\n";
    out << "#include <DelusiveExternal/DelusiveScriptAPI.h>\n";
    out << "#include \"DelusiveScripts.h\"\n\n";
    out << "#define REGISTER_ENEMYLOGIC(REGISTRY, CLASS_NAME) \\\n"
        "    do { REGISTRY.RegisterEnemyLogic(#CLASS_NAME, [](){ return std::make_unique<CLASS_NAME>(); }); } while(0)\n";
    out << "#define REGISTER_UISCRIPT(REGISTRY, CLASS_NAME) \\\n"
        "    do { REGISTRY.RegisterUIScript(#CLASS_NAME, [](){ return std::make_unique<CLASS_NAME>(); }); } while(0)\n\n";

    // Include all discovered scripts
    for (const auto& name : enemyScripts)
        out << "#include \"EnemyLogic/" << name << ".h\"\n";
    for (const auto& name : uiScripts)
        out << "#include \"UI/" << name << ".h\"\n";
    out << "\n";

    // Write InitializeScripts()
    out << "extern \"C\" __declspec(dllexport)\n";
    out << "void InitializeScripts(ScriptRegistry& registry) {\n";
    for (const auto& name : enemyScripts)
        out << "    REGISTER_ENEMYLOGIC(registry, " << name << ");\n";
    for (const auto& name : uiScripts)
        out << "    REGISTER_UISCRIPT(registry, " << name << ");\n";
    out << "}\n\n";

    // Write the stubs
    out << "extern \"C\" __declspec(dllexport)\n";
    out << "void UpdateScripts(float) {}\n";
    out << "extern \"C\" __declspec(dllexport)\n";
    out << "void ShutdownScripts() {}\n";

    out.close();
    std::cout << "Generated " << output << " successfully.\n";
    return 0;
}